services:
  ansible-controller:
    image: almalinux:9
    container_name: ansible-controller
    hostname: ansible-controller
    privileged: true
    volumes:
      - ./ansible:/ansible
    networks:
      - haproxy_network
    command: >
      bash -c "
        dnf install -y epel-release &&
        dnf update -y &&
        dnf install -y ansible-core openssh-clients &&
        ssh-keygen -t rsa -N '' -f /root/.ssh/id_rsa &&
        cat /root/.ssh/id_rsa.pub > /ansible/id_rsa.pub &&
        tail -f /dev/null
      "

  haproxy1:
    image: almalinux:9
    container_name: haproxy1
    hostname: haproxy1
    privileged: true
    networks:
      - haproxy_network
    volumes:
      - ./ansible:/ansible
    command: >
      bash -c "
        dnf install -y openssh-server &&
        ssh-keygen -A &&
        mkdir -p /root/.ssh &&
        cat /ansible/id_rsa.pub >> /root/.ssh/authorized_keys &&
        chmod 600 /root/.ssh/authorized_keys &&
        /usr/sbin/sshd -D
      "

  haproxy2:
    image: almalinux:9
    container_name: haproxy2
    hostname: haproxy2
    privileged: true
    networks:
      - haproxy_network
    volumes:
      - ./ansible:/ansible
    command: >
      bash -c "
        dnf install -y openssh-server &&
        ssh-keygen -A &&
        mkdir -p /root/.ssh &&
        cat /ansible/id_rsa.pub >> /root/.ssh/authorized_keys &&
        chmod 600 /root/.ssh/authorized_keys &&
        /usr/sbin/sshd -D
      "

networks:
  haproxy_network:
    driver: bridge
