services:
  ansible-controller:
    image: almalinux:9
    container_name: ansible-controller
    hostname: ansible-controller
    privileged: true
    volumes:
      - ./ansible:/ansible
    networks:
      - haproxy_network
    command: >
      bash -c "
        dnf install -y epel-release &&
        dnf update -y &&
        dnf install -y ansible-core openssh-clients &&
        tail -f /dev/null
      "

  haproxy1:
    image: almalinux:9
    container_name: haproxy1
    hostname: haproxy1
    privileged: true
    networks:
      - haproxy_network
    command: >
      bash -c "
        dnf install -y openssh-server &&
        dnf update -y &&
        ssh-keygen -A &&
        /usr/sbin/sshd &&
        tail -f /dev/null
      "

  haproxy2:
    image: almalinux:9
    container_name: haproxy2
    hostname: haproxy2
    privileged: true
    networks:
      - haproxy_network
    command: >
      bash -c "
        dnf install -y openssh-server &&
        dnf update -y &&
        ssh-keygen -A &&
        /usr/sbin/sshd &&
        tail -f /dev/null
      "

networks:
  haproxy_network:
    driver: bridge
