---
- name: setup load-balancer server
  hosts: all
  become: yes
  roles:
    #- { role: firewalld,  tags: firewalld }
    - { role: haproxy,    tags: haproxy }
    - { role: keepalived, tags: keepalived }
  vars:
    enable_keepalived_autostart: false
