---
- name: 疎通チェック
  hosts: all
  become: yes
  tasks:
    - name: hostnameコマンドを実行
      command: hostname
      register: hostname_result

    - name: 結果を表示
      debug:
        msg: "{{ inventory_hostname }}のホスト名: {{ hostname_result.stdout }}"
